CREATE DATABASE dbs;
CREATE DATABASE nodebb;
CREATE USER mainbackend WITH PASSWORD '114514';
--生产环境中需要更改密码
GRANT ALL PRIVILEGES ON DATABASE dbs TO mainbackend;
GRANT ALL PRIVILEGES ON DATABASE nodebb TO mainbackend;
CREATE USER nodebb WITH PASSWORD '114514';
GRANT ALL PRIVILEGES ON DATABASE nodebb TO nodebb;